name: CI

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    check:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - uses: cachix/install-nix-action@v31

            - name: Format
              run: nix develop --command gofmt -l -s -w .

            - name: Vet
              run: nix develop --command go vet ./...

            - name: Staticcheck
              run: nix develop --command staticcheck ./...

            - name: Test
              run: nix develop --command go test -v ./...
